"""initial schema

Revision ID: 20e685d6a26f
Revises: 
Create Date: 2026-01-13 15:09:22.524225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20e685d6a26f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('podcast_data',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('podcast_name', sa.Text(), nullable=True),
    sa.Column('length_minutes', sa.Integer(), nullable=True),
    sa.Column('release_time', sa.DateTime(), nullable=True),
    sa.Column('intro_length_seconds', sa.Integer(), nullable=True),
    sa.Column('adsNumber', sa.Integer(), nullable=True),
    sa.Column('previous_ep_retention', sa.Integer(), nullable=True),
    sa.Column('host_energy', sa.Integer(), nullable=True),
    sa.Column('completion_percentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('podcast_data')
    # ### end Alembic commands ###
