"""add category to podcast_data

Revision ID: f136ba0c84e4
Revises: 20e685d6a26f
Create Date: 2026-01-13 15:20:39.518821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f136ba0c84e4'
down_revision: Union[str, Sequence[str], None] = '20e685d6a26f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('podcast_data', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('podcast_data', 'category')
    # ### end Alembic commands ###
